### ISSUE TITLE
shuffle requirement

### ISSUE THREAD

**Issue by dt990pro** [cs361fall2017/team12#4]
// shuffles the deck so that it is random

when the deck created, shuffle the deck.
switch the random card with the first card.
keep doing 30-50 times, the deck will be shuffled.

time estimate: 10-20mins

**Comment by chiayutang** [comment]
This is a good idea!! I think you can do more than 50 times.

**Comment by lijinf** [comment]
50 times are not enough, I think at least 100 times to make card fully shuffled.

**Comment by MaoYihui** [comment]
I think 50 times is much enough.
